#!/bin/bash
# Apre Terminal ed esegue lo script deploy
osascript -e 'tell application "Terminal"
    activate
    do script "cd /Users/michelemarri/Sites/metodo-design-system && ./deploy.sh"
end tell'

